### ISSUE TITLE
Error installing dependencies 

### ISSUE THREAD

**Issue by tatecarson** [wavesjs/waves-lfo#1]
Hi, 

I'm trying to try out your library but I'm having problems getting the examples running. After `npm install` I get all the way to here: 
```
[es6-prototyping-boilerplate]	src/Synth.js: successfully transpiled to "dist/Synth.js" (416ms)
[es6-prototyping-boilerplate]	src/WaveformTrack.js: successfully transpiled to "dist/WaveformTrack.js" (87ms)
[es6-prototyping-boilerplate]	src/analyzer.js: successfully transpiled to "dist/analyzer.js" (123ms)
[es6-prototyping-boilerplate]	src/index.js: successfully transpiled to "dist/index.js" (157ms)
[es6-prototyping-boilerplate]	src/script.js: successfully transpiled to "dist/script.js" (64ms)
[es6-prototyping-boilerplate]	bundle.js: bundle error
> Cannot find module 'waves-lfo/client' from '/Users/tatecarson/Documents/webDev/waves-lfo/examples/mosaicking/dist'
[es6-prototyping-boilerplate]	bundle.js: bundle error
> Cannot find module 'waves-lfo/common' from '/Users/tatecarson/Documents/webDev/waves-lfo/examples/mosaicking/dist'
es6-prototyping-boilerplate@1.0.1 /Users/tatecarson/Documents/webDev/waves-lfo/examples/mosaicking
├── @ircam/waves-lfo@1.1.0  extraneous (git://github.com/wavesjs/waves-lfo.git#409cda5c0a417db1682324d44c206d781998f3c4)
```

it looks like it's failing on installing your packages for some reason. Any advice? I'm really interested in trying it out.

**Comment by b-ma** [comment]
Hey, 

Thanks for the feedback ? We are currently deploying the library on npm and the migration is not fully cleaned / finished. This should be fixed within a day.

Besides, the final npm target will be https://www.npmjs.com/package/waves-lfo

**Comment by b-ma** [comment]
Hi,

It should be fixed now, could you re-clone the repo and confirm its ok on your side ?

Thx

**Comment by tatecarson** [comment]
Ok, it works now. To try the examples should I first run npm install on each folder? I'm a bit new to the package management thing. Thanks.

**Comment by b-ma** [comment]
Yes that's the idea. You can also see the examples online, links are on the homepage of the repository.
